const integrations = {
  stripe: {
    name: 'Stripe',
    icon: '💳',
    category: 'payment',
    description: 'Payment processing and subscriptions',
    auth: 'api_key',
    enabled: true,
    endpoints: ['/api/integrations/stripe/*'],
  },
  twilio: {
    name: 'Twilio',
    icon: '📞',
    category: 'communication',
    description: 'Phone, SMS, and voice automation',
    auth: 'api_key',
    enabled: true,
    endpoints: ['/api/integrations/twilio/*'],
  },
  googleMaps: {
    name: 'Google Maps',
    icon: '🗺️',
    category: 'location',
    description: 'Location data and business discovery',
    auth: 'api_key',
    enabled: true,
    endpoints: ['/api/integrations/google-maps/*'],
  },
  gemini: {
    name: 'Google Gemini',
    icon: '🧠',
    category: 'ai',
    description: 'Advanced AI reasoning and analysis',
    auth: 'api_key',
    enabled: true,
    endpoints: ['/api/integrations/gemini/*'],
  },
  perplexity: {
    name: 'Perplexity AI',
    icon: '🔍',
    category: 'research',
    description: 'Web research and information synthesis',
    auth: 'api_key',
    enabled: true,
    endpoints: ['/api/integrations/perplexity/*'],
  },
  julius: {
    name: 'Julius AI',
    icon: '📊',
    category: 'analytics',
    description: 'Data analysis and reporting',
    auth: 'api_key',
    enabled: true,
    endpoints: ['/api/integrations/julius/*'],
  },
  lovable: {
    name: 'Lovable.dev',
    icon: '🎨',
    category: 'ui_generation',
    description: 'AI-powered UI and component generation',
    auth: 'api_key',
    enabled: true,
    features: ['ui_generation', 'component_library', 'design_system'],
    endpoints: ['/api/integrations/lovable/*'],
  },
  emergent: {
    name: 'Emergent.ai',
    icon: '🤖',
    category: 'autonomous_agents',
    description: 'Autonomous AI agent orchestration',
    auth: 'api_key',
    enabled: true,
    features: ['agent_creation', 'agent_orchestration', 'autonomous_execution'],
    endpoints: ['/api/integrations/emergent/*'],
  },
  replit: {
    name: 'Replit',
    icon: '💻',
    category: 'development',
    description: 'Cloud IDE and app deployment',
    auth: 'oauth2',
    enabled: true,
    features: ['code_execution', 'deployment', 'collaboration'],
    endpoints: ['/api/integrations/replit/*'],
  },
  claude: {
    name: 'Claude (Anthropic)',
    icon: '🧬',
    category: 'ai',
    description: 'Advanced conversational AI and reasoning',
    auth: 'api_key',
    enabled: true,
    features: ['text_generation', 'code_generation', 'analysis'],
    endpoints: ['/api/integrations/claude/*'],
  },
  github: {
    name: 'GitHub',
    icon: '🐙',
    category: 'development',
    description: 'Repository management and automation',
    auth: 'oauth2',
    enabled: true,
    features: ['repo_management', 'pull_requests', 'automation', 'webhooks'],
    endpoints: ['/api/integrations/github/*'],
  },
  vercel: {
    name: 'Vercel',
    icon: '▲',
    category: 'deployment',
    description: 'Serverless deployment and CDN',
    auth: 'api_key',
    enabled: true,
    features: ['deployment', 'analytics', 'edge_functions', 'preview_urls'],
    endpoints: ['/api/integrations/vercel/*'],
  },
  googleCloud: {
    name: 'Google Cloud',
    icon: '☁️',
    category: 'infrastructure',
    description: 'Cloud computing and services',
    auth: 'service_account',
    enabled: true,
    features: ['compute', 'storage', 'firestore', 'cloud_functions'],
    endpoints: ['/api/integrations/google-cloud/*'],
  },
  googleSheets: {
    name: 'Google Sheets (Stitch)',
    icon: '📈',
    category: 'data_integration',
    description: 'Data sync and spreadsheet automation',
    auth: 'oauth2',
    enabled: true,
    features: ['data_sync', 'real_time_updates', 'automation'],
    endpoints: ['/api/integrations/google-sheets/*'],
  },
  antigravity: {
    name: 'AntiGravity.ai',
    icon: '⚡',
    category: 'data_pipeline',
    description: 'Automated data pipeline and ETL',
    auth: 'api_key',
    enabled: true,
    features: ['etl', 'data_transformation', 'automation', 'scheduling'],
    endpoints: ['/api/integrations/antigravity/*'],
  },
  openclaw: {
    name: 'OpenClaw.ai',
    icon: '🦾',
    category: 'automation',
    description: 'Autonomous task execution and workflow',
    auth: 'api_key',
    enabled: true,
    features: ['task_automation', 'workflow_execution', 'intelligent_routing'],
    endpoints: ['/api/integrations/openclaw/*'],
  },
};

module.exports = integrations;
